# -*- coding: utf-8 -*-
"""iris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n5tCgr2WSPvvqFUdwpR3Bd5lU76EwFJv
"""

from google.colab import files

# This will prompt you to select a file from your computer
uploaded = files.upload()

# Verify the upload
print("Uploaded files:")
for filename in uploaded.keys():
    print(f"- {filename} ({len(uploaded[filename])} bytes)")

# Now you can access the file as 'Iris.csv'
import pandas as pd
df = pd.read_csv('Iris.csv')

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Load data (adjust path based on your upload method)
df = pd.read_csv('Iris.csv')

# Show basic info
df.info()

# Visualize the data
sns.pairplot(df, hue='Species')
plt.show()

# Preprocess
df = df.drop('Id', axis=1)
label_encoder = LabelEncoder()
df['Species'] = label_encoder.fit_transform(df['Species'])

# Split data
X = df.drop('Species', axis=1)
y = df['Species']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Evaluate
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Confusion matrix visualization
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=label_encoder.classes_,
            yticklabels=label_encoder.classes_)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()